// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "hiroCommonStatus.hpp"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



_init_in_def_( const ::CORBA::Short hiroCommonStatus::ANGLE_UPPER_LIMIT_ERROR = 1; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::ANGLE_LOWER_LIMIT_ERROR = 2; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::INVERSE_KINEMA_ERROR = 3; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_VALUE_LENGTH_ERROR = 16; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_1_VALUE_LENGTH_ERROR = 17; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_2_VALUE_LENGTH_ERROR = 18; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_3_VALUE_LENGTH_ERROR = 19; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_4_VALUE_LENGTH_ERROR = 20; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_5_VALUE_LENGTH_ERROR = 21; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_6_VALUE_LENGTH_ERROR = 22; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_7_VALUE_LENGTH_ERROR = 23; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_8_VALUE_LENGTH_ERROR = 24; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_9_VALUE_LENGTH_ERROR = 25; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_10_VALUE_LENGTH_ERROR = 26; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_11_VALUE_LENGTH_ERROR = 27; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_12_VALUE_LENGTH_ERROR = 28; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_13_VALUE_LENGTH_ERROR = 29; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_14_VALUE_LENGTH_ERROR = 30; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_15_VALUE_LENGTH_ERROR = 31; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::IN_KIND_ERROR = 4096; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::OUT_KIND_ERROR = 4097; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::JOINT_NUM_ERROR = 4098; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::PART_NUM_ERROR = 4099; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::PLUGIN_NAME_ERROR = 4100; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::KIND_ERROR = 8192; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::VALUE_ZERO_ERROR = 8193; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::MISSMATCH_ERROR = 8194; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::INI_JOINT_ERROR = 8195; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::VALUE_JOINT_ERROR = 8196; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::FIRST_TIME_ERROR = 8197; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::OTHER_MOTION_ERROR = 8198; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::TIME_CHANGE_WARNING = 8199; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::FIRST_POINT_ERROR = 8200; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::FALL_ON_JOINT_ERROR = 8201; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::SPEED_ZERO_ERROR = 8202; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::PROTECTIVE_STOP_ERROR = 8203; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::SERVO_STATUS_ERROR = 12288; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::NO_CONTENTS_SEQ_ERROR = 12289; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::SAME_JOINT_SEQ_ERROR = 12290; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::NOT_SPECIFIED_JOINT_ERROR = 12291; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::UNKNOWN_JOINT_ERROR = 12292; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::INPUT_ANGLE_ERROR = 12293; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::CALIB_ANGLE_ERROR = 12294; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::RE_CALIBRATION = 12295; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::EMERGENCY_ERROR = 12296; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::MOVE_FOR_ZPOS_ERROR = 12299; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::CALIBRATION_ERROR = 12300; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::SERVO_ON_ERROR = 12301; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::GET_MC_ERROR = 12302; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::MOVE_TO_CALIB_SERVO_ERROR = 16385; )

_init_in_def_( const ::CORBA::Short hiroCommonStatus::MOVE_TO_CALIB_ERROR = 20481; )

