// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "systemCommand.hpp"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



const char * systemCommand::versionStringIDL = "47:4ef213af09ec";

const char * systemCommand::versionDateIDL = "Tue Jan 27 16:40:51 2009 +0900";

systemCommand_ptr systemCommand_Helper::_nil() {
  return ::systemCommand::_nil();
}

::CORBA::Boolean systemCommand_Helper::is_nil(::systemCommand_ptr p) {
  return ::CORBA::is_nil(p);

}

void systemCommand_Helper::release(::systemCommand_ptr p) {
  ::CORBA::release(p);
}

void systemCommand_Helper::marshalObjRef(::systemCommand_ptr obj, cdrStream& s) {
  ::systemCommand::_marshalObjRef(obj, s);
}

systemCommand_ptr systemCommand_Helper::unmarshalObjRef(cdrStream& s) {
  return ::systemCommand::_unmarshalObjRef(s);
}

void systemCommand_Helper::duplicate(::systemCommand_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

systemCommand_ptr
systemCommand::_duplicate(::systemCommand_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

systemCommand_ptr
systemCommand::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


systemCommand_ptr
systemCommand::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

systemCommand_ptr
systemCommand::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_systemCommand _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_systemCommand* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_systemCommand;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* systemCommand::_PD_repoId = "IDL:systemCommand:1.0";


_objref_systemCommand::~_objref_systemCommand() {
  
}


_objref_systemCommand::_objref_systemCommand(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::systemCommand::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_systemCommand::_ptrToObjRef(const char* id)
{
  if( id == ::systemCommand::_PD_repoId )
    return (::systemCommand_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::systemCommand::_PD_repoId) )
    return (::systemCommand_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  void_i_cstring_i_cstring_o_cstring
class _0RL_cd_0C80E0B9850984F9_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_0C80E0B9850984F9_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::String_var arg_2;
};

void _0RL_cd_0C80E0B9850984F9_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);

}

void _0RL_cd_0C80E0B9850984F9_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();

}

void _0RL_cd_0C80E0B9850984F9_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalString(arg_2,0);

}

void _0RL_cd_0C80E0B9850984F9_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  arg_2 = _n.unmarshalString(0);

}

// Local call call-back function.
static void
_0RL_lcfn_0C80E0B9850984F9_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_0C80E0B9850984F9_00000000* tcd = (_0RL_cd_0C80E0B9850984F9_00000000*)cd;
  _impl_systemCommand* impl = (_impl_systemCommand*) svnt->_ptrToInterface(systemCommand::_PD_repoId);
  impl->function(tcd->arg_0, tcd->arg_1, tcd->arg_2.out());


}

void _objref_systemCommand::function(const char* command, const char* argv, ::CORBA::String_out cout)
{
  _0RL_cd_0C80E0B9850984F9_00000000 _call_desc(_0RL_lcfn_0C80E0B9850984F9_10000000, "function", 9);
  _call_desc.arg_0 = command;
  _call_desc.arg_1 = argv;

  _invoke(_call_desc);
  cout = _call_desc.arg_2._retn();


}
_pof_systemCommand::~_pof_systemCommand() {}


omniObjRef*
_pof_systemCommand::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_systemCommand(ior, id);
}


::CORBA::Boolean
_pof_systemCommand::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::systemCommand::_PD_repoId) )
    return 1;
  
  return 0;
}

const _pof_systemCommand _the_pof_systemCommand;

_impl_systemCommand::~_impl_systemCommand() {}


::CORBA::Boolean
_impl_systemCommand::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "function") ) {

    _0RL_cd_0C80E0B9850984F9_00000000 _call_desc(_0RL_lcfn_0C80E0B9850984F9_10000000, "function", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_systemCommand::_ptrToInterface(const char* id)
{
  if( id == ::systemCommand::_PD_repoId )
    return (::_impl_systemCommand*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::systemCommand::_PD_repoId) )
    return (::_impl_systemCommand*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
_impl_systemCommand::_mostDerivedRepoId()
{
  return ::systemCommand::_PD_repoId;
}

POA_systemCommand::~POA_systemCommand() {}

